#!/bin/sh

mkdir -p /tmp/build-app/app

bun install
BUILD_PATH='/tmp/build-app/app' bun run build
cp Dockerfile /tmp/build-app
cp default.conf /tmp/build-app
cp ngx_http_auth_request_module_config /tmp/build-app