# Generated by Django 4.2.5 on 2023-09-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mail",
            name="data",
        ),
        migrations.AddField(
            model_name="mail",
            name="html",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="mail",
            name="subject",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="mail",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
