# Generated by Django 4.2.5 on 2023-09-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0002_remove_mail_data_mail_html_mail_subject_mail_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="attachment",
            name="type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="mail",
            name="dkim",
            field=models.CharField(default="{}", max_length=255),
        ),
        migrations.AddField(
            model_name="mail",
            name="sender_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mail",
            name="spf",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
