# Generated by Django 4.2.5 on 2023-09-29 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mail", "0003_attachment_name_attachment_type_mail_dkim_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mail",
            name="envelope",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="mail",
            name="from_sender",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="mail",
            name="to_recipients",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="mail",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
