# Generated by Django 4.2.5 on 2023-10-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0007_userfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="mail",
            name="pending_webhook",
            field=models.BooleanField(default=False),
        ),
    ]
