# Generated by Django 4.2.5 on 2023-11-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0010_remove_attachment_uri_file_uri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="uri",
            field=models.CharField(
                blank=True, db_column="uri", max_length=255, null=True
            ),
        ),
        migrations.RenameField(
            model_name="file",
            old_name="uri",
            new_name="_uri",
        ),
    ]
