# Generated by Django 4.2.5 on 2023-12-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0011_alter_file_uri_rename_uri_file__uri"),
    ]

    operations = [
        migrations.AddField(
            model_name="mail",
            name="notebook_mail",
            field=models.BooleanField(default=False),
        ),
    ]
