# Generated by Django 4.2.5 on 2023-12-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0012_mail_notebook_mail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="notebook_mail",
            field=models.IntegerField(default=-1),
        ),
    ]
