# Generated by Django 4.2.5 on 2023-10-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountmodel",
            name="headers",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="accountmodel",
            name="webhook",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
