# Generated by Django 4.2.5 on 2023-11-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0004_accountmodel_send_attachments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountmodel",
            name="send_attachments",
        ),
        migrations.AddField(
            model_name="accountmodel",
            name="locked",
            field=models.BooleanField(default=False),
        ),
    ]
