# Generated by Django 4.2.5 on 2023-12-04 13:42

from django.db import migrations, models
import redttg_mail_backend.auth_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0005_remove_accountmodel_send_attachments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountmodel",
            name="notebook_repr",
            field=models.TextField(
                default=redttg_mail_backend.auth_app.models.make_repr,
                editable=False,
                max_length=12,
            ),
        ),
    ]
