# Generated by Django 4.2.5 on 2023-12-04 14:05

from django.db import migrations, models
import redttg_mail_backend.auth_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0006_accountmodel_notebook_repr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountmodel",
            name="notebook_repr",
            field=models.TextField(
                default=redttg_mail_backend.auth_app.models.make_repr,
                editable=False,
                max_length=20,
            ),
        ),
    ]
